CREATE EVENT SESSION [IX Wartung] ON SERVER 
ADD EVENT sqlserver.index_defragmentation(
    ACTION(sqlserver.context_info,sqlserver.database_name,sqlserver.sql_text))
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=30 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
GO


